### ISSUE TITLE
add prepare.sh to run all the preparation commands

### ISSUE THREAD

**Issue by dachafra** [anifledramos/tfm-rdf#2]
and the mvn clean install
#### JNITriples
javac -cp ../../../target/hdt-java-core-2.0.jar:../../../../hdt-api/target/hdt-api-2.0.jar -h . org/rdfhdt/hdt/triples/impl/JNITriples.java 

#### JNIDictionary
javac -cp ../../../target/hdt-java-core-2.0.jar:../../../../hdt-api/target/hdt-api-2.0.jar -h . org/rdfhdt/hdt/dictionary/impl/section/JNIDictionarySection.java

**Comment by anifledramos** [comment]
Added prepare.sh to run preparations commands and corrected some explanations in README. 
Both javac commands are only necessary if you want to implement new JNIAdapters from Java to C/C++ since they generate the headers file for the JNI communicaion, they are not needed to run the example. 
Please elaborate on the "mvn clean install", I added that as a final line on prepare.sh but I am not sure if that was what you meant.
